/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrendingRouteImport } from './routes/api.trending'
import { Route as ApiReposOwnerRepoReadmeRouteImport } from './routes/api.repos.$owner.$repo.readme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendingRoute = ApiTrendingRouteImport.update({
  id: '/api/trending',
  path: '/api/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposOwnerRepoReadmeRoute = ApiReposOwnerRepoReadmeRouteImport.update({
  id: '/api/repos/$owner/$repo/readme',
  path: '/api/repos/$owner/$repo/readme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/repos/$owner/$repo/readme': typeof ApiReposOwnerRepoReadmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/repos/$owner/$repo/readme': typeof ApiReposOwnerRepoReadmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/repos/$owner/$repo/readme': typeof ApiReposOwnerRepoReadmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/trending' | '/api/repos/$owner/$repo/readme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/trending' | '/api/repos/$owner/$repo/readme'
  id: '__root__' | '/' | '/api/trending' | '/api/repos/$owner/$repo/readme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTrendingRoute: typeof ApiTrendingRoute
  ApiReposOwnerRepoReadmeRoute: typeof ApiReposOwnerRepoReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trending': {
      id: '/api/trending'
      path: '/api/trending'
      fullPath: '/api/trending'
      preLoaderRoute: typeof ApiTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos/$owner/$repo/readme': {
      id: '/api/repos/$owner/$repo/readme'
      path: '/api/repos/$owner/$repo/readme'
      fullPath: '/api/repos/$owner/$repo/readme'
      preLoaderRoute: typeof ApiReposOwnerRepoReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTrendingRoute: ApiTrendingRoute,
  ApiReposOwnerRepoReadmeRoute: ApiReposOwnerRepoReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
