/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRadarRouteImport } from './routes/api.radar'
import { Route as NextopCliSearchRouteImport } from './routes/nextop.cli.search'
import { Route as NextopCliItemRouteImport } from './routes/nextop.cli.item'
import { Route as NextopCliBoardRouteImport } from './routes/nextop.cli.board'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const NextopCliSearchRoute = NextopCliSearchRouteImport.update({
  id: '/nextop/cli/search',
  path: '/nextop/cli/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NextopCliItemRoute = NextopCliItemRouteImport.update({
  id: '/nextop/cli/item',
  path: '/nextop/cli/item',
  getParentRoute: () => rootRouteImport,
} as any)
const NextopCliBoardRoute = NextopCliBoardRouteImport.update({
  id: '/nextop/cli/board',
  path: '/nextop/cli/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/nextop/cli/board': typeof NextopCliBoardRoute
  '/nextop/cli/item': typeof NextopCliItemRoute
  '/nextop/cli/search': typeof NextopCliSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/nextop/cli/board': typeof NextopCliBoardRoute
  '/nextop/cli/item': typeof NextopCliItemRoute
  '/nextop/cli/search': typeof NextopCliSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/nextop/cli/board': typeof NextopCliBoardRoute
  '/nextop/cli/item': typeof NextopCliItemRoute
  '/nextop/cli/search': typeof NextopCliSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/radar'
    | '/nextop/cli/board'
    | '/nextop/cli/item'
    | '/nextop/cli/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/radar'
    | '/nextop/cli/board'
    | '/nextop/cli/item'
    | '/nextop/cli/search'
  id:
    | '__root__'
    | '/'
    | '/api/radar'
    | '/nextop/cli/board'
    | '/nextop/cli/item'
    | '/nextop/cli/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRadarRoute: typeof ApiRadarRoute
  NextopCliBoardRoute: typeof NextopCliBoardRoute
  NextopCliItemRoute: typeof NextopCliItemRoute
  NextopCliSearchRoute: typeof NextopCliSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nextop/cli/search': {
      id: '/nextop/cli/search'
      path: '/nextop/cli/search'
      fullPath: '/nextop/cli/search'
      preLoaderRoute: typeof NextopCliSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nextop/cli/item': {
      id: '/nextop/cli/item'
      path: '/nextop/cli/item'
      fullPath: '/nextop/cli/item'
      preLoaderRoute: typeof NextopCliItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nextop/cli/board': {
      id: '/nextop/cli/board'
      path: '/nextop/cli/board'
      fullPath: '/nextop/cli/board'
      preLoaderRoute: typeof NextopCliBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRadarRoute: ApiRadarRoute,
  NextopCliBoardRoute: NextopCliBoardRoute,
  NextopCliItemRoute: NextopCliItemRoute,
  NextopCliSearchRoute: NextopCliSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
