/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRadarRouteImport } from './routes/api.radar'
import { Route as TuttiCliSearchRouteImport } from './routes/tutti.cli.search'
import { Route as TuttiCliItemRouteImport } from './routes/tutti.cli.item'
import { Route as TuttiCliBoardRouteImport } from './routes/tutti.cli.board'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TuttiCliSearchRoute = TuttiCliSearchRouteImport.update({
  id: '/tutti/cli/search',
  path: '/tutti/cli/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TuttiCliItemRoute = TuttiCliItemRouteImport.update({
  id: '/tutti/cli/item',
  path: '/tutti/cli/item',
  getParentRoute: () => rootRouteImport,
} as any)
const TuttiCliBoardRoute = TuttiCliBoardRouteImport.update({
  id: '/tutti/cli/board',
  path: '/tutti/cli/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/tutti/cli/board': typeof TuttiCliBoardRoute
  '/tutti/cli/item': typeof TuttiCliItemRoute
  '/tutti/cli/search': typeof TuttiCliSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/tutti/cli/board': typeof TuttiCliBoardRoute
  '/tutti/cli/item': typeof TuttiCliItemRoute
  '/tutti/cli/search': typeof TuttiCliSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/radar': typeof ApiRadarRoute
  '/tutti/cli/board': typeof TuttiCliBoardRoute
  '/tutti/cli/item': typeof TuttiCliItemRoute
  '/tutti/cli/search': typeof TuttiCliSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/radar'
    | '/tutti/cli/board'
    | '/tutti/cli/item'
    | '/tutti/cli/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/radar'
    | '/tutti/cli/board'
    | '/tutti/cli/item'
    | '/tutti/cli/search'
  id:
    | '__root__'
    | '/'
    | '/api/radar'
    | '/tutti/cli/board'
    | '/tutti/cli/item'
    | '/tutti/cli/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRadarRoute: typeof ApiRadarRoute
  TuttiCliBoardRoute: typeof TuttiCliBoardRoute
  TuttiCliItemRoute: typeof TuttiCliItemRoute
  TuttiCliSearchRoute: typeof TuttiCliSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutti/cli/search': {
      id: '/tutti/cli/search'
      path: '/tutti/cli/search'
      fullPath: '/tutti/cli/search'
      preLoaderRoute: typeof TuttiCliSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutti/cli/item': {
      id: '/tutti/cli/item'
      path: '/tutti/cli/item'
      fullPath: '/tutti/cli/item'
      preLoaderRoute: typeof TuttiCliItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutti/cli/board': {
      id: '/tutti/cli/board'
      path: '/tutti/cli/board'
      fullPath: '/tutti/cli/board'
      preLoaderRoute: typeof TuttiCliBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRadarRoute: ApiRadarRoute,
  TuttiCliBoardRoute: TuttiCliBoardRoute,
  TuttiCliItemRoute: TuttiCliItemRoute,
  TuttiCliSearchRoute: TuttiCliSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
