#!/bin/sh
set -eu

: "${NEXTOP_APP_PACKAGE_DIR:?}"
: "${NEXTOP_APP_HOST:?}"
: "${NEXTOP_APP_PORT:?}"
: "${NEXTOP_APP_DATA_DIR:?}"
: "${NEXTOP_APP_NODE:?}"

export HOST="$NEXTOP_APP_HOST"
export PORT="$NEXTOP_APP_PORT"
export NEXTOP_APP_DATA_DIR

exec "$NEXTOP_APP_NODE" "$NEXTOP_APP_PACKAGE_DIR/server.mjs"
